authors:
- Lukasz Wencel (https://github.com/lwencel-priv)
build_ignore:
- .github
- .gitignore
- .tox
- .venv
- .vscode
- build
- example
- Makefile
- requirements-test.txt
- plugins/tests
- tox_files
- tox.ini
dependencies: {}
description: Proxmox VE Ansible Collection
documentation: https://github.com/Margays/ansible-proxmox/blob/main/README.md
homepage: http://github.com/Margays/ansible-proxmox
issues: http://github.com/Margays/ansible-proxmox/issues
license_file: LICENSE
name: proxmox
namespace: margays
readme: README.md
repository: http://github.com/Margays/ansible-proxmox
tags:
- proxmox
- vm
- cluster
version: 2.4.0
