---
- name: Configure proxmox
  hosts: proxmox
  tasks:
    # - name: Delete VM
    #   margays.proxmox.node_qemu:
    #     node: "testprox"
    #     vmid: "101"
    #     destroy_unreferenced_disks: true
    #     state: absent

    - name: Create VM
      margays.proxmox.node_qemu:
        node: "testprox"
        vmid: "101"
        name: "testvm"
        cores: 2
        memory: 4096
        tags: "test"
        pool: "test"
        net:
          - idx: 0
            model: virtio
            bridge: vmbr0
            tag: 102
          - idx: 1
            model: virtio
            bridge: vmbr0
            tag: 102
          - idx: 2
            model: virtio
            bridge: vmbr0
            tag: 103
        scsi:
          - idx: 0
            storage: local-lvm
            size: 1
            cache: writeback
        ide:
          - idx: 0
            storage: local-lvm
            size: 1
            cache: writeback
        sata:
          - idx: 0
            storage: local-lvm
            size: 1
            cache: writeback
        virtio:
          - idx: 0
            storage: local-lvm
            size: 1
            cache: writeback

        # Delete options
        destroy_unreferenced_disks: true
        state: present
      register: result

    - name: Print result
      debug:
        var: result
