---
- name: Configure proxmox
  hosts: proxmox
  tasks:
    - name: Setup proxmox pool
      margays.proxmox.pool:
        poolid: "test"
        comment: "Test pool"
        state: present

    - name: Configure cluster options
      margays.proxmox.cluster_options:
        description: "Proxmox Casiopeia Cluster!"
        max_workers: "3"

    - name: Delte VM 101
      margays.proxmox.node_qemu:
        node: "testprox"
        vmid: "101"
        state: absent

    - name: Create VM
      margays.proxmox.node_qemu:
        node: "testprox"
        vmid: "101"
        name: "testvm"
        cores: 4
        memory: 4096
        tags: "test"
        pool: "test"
        net:
          - idx: 0
            model: virtio
            bridge: vmbr0
            tag: 101
          - idx: 1
            model: virtio
            bridge: vmbr0
            tag: 102
          - idx: 2
            model: virtio
            bridge: vmbr0
            tag: 103
        scsi:
          - idx: 0
            file: local-lvm:1
            cache: writeback
        ide:
          - idx: 0
            file: local-lvm:1
            cache: writeback
        sata:
          - idx: 0
            file: local-lvm:1
            cache: writeback
        virtio:
          - idx: 0
            file: local-lvm:1
            cache: writeback

        # Delete options
        destroy_unreferenced_disks: true
        state: present
