all:
  hosts:
    odroid01:
      ansible_host: 192.168.4.8
    k8s01:
      ansible_host: 192.168.4.3
    k8s02:
      ansible_host: 192.168.4.4
    k8s03:
      ansible_host: 192.168.4.5
  children:
    proxmox:
      hosts:
        odroid01:
    k8s_cluster:
      children:
        kube_control_plane:
          hosts:
            k8s01:
        kube_node:
          hosts:
            k8s01:
            k8s02:
            k8s03:
        etcd:
          hosts:
            k8s01:
